### ISSUE TITLE
Detect Media/File support

### ISSUE THREAD

**Issue by FayasNoushad** [AbirHasan2005/Rename-Bot#12]
Please provide detecting media or file support

**Comment by AbirHasan2005** [comment]
https://github.com/AbirHasan2005/Rename-Bot/blob/3a5c3aa061a66a202072c552f220ee98eeeba22e/bot/plugins/rename.py#L74

This? 🤔

**Comment by FayasNoushad** [comment]
> https://github.com/AbirHasan2005/Rename-Bot/blob/3a5c3aa061a66a202072c552f220ee98eeeba22e/bot/plugins/rename.py#L74
> 
> This? thinking

No, without command support.

**Comment by AbirHasan2005** [comment]
Just after sending or forwarding any media right? 👀

**Comment by FayasNoushad** [comment]
> Just after sending or forwarding any media right? eyes

Yes

**Comment by AbirHasan2005** [comment]
Check now 👀
