### ISSUE TITLE
#commands not working

### ISSUE THREAD

**Issue by rubandurai27** [AbirHasan2005/Rename-Bot#14]
![Screenshot_2021-12-02-06-37-34-035_org telegram plus](https://user-images.githubusercontent.com/77948100/144339292-b274011e-54bc-4407-924f-866bc63ab6c6.jpg)

/broadcast & /status commands are not working

**Comment by AbirHasan2005** [comment]
You added your Telegram user_id in `OWNER_ID` variable?
