### ISSUE TITLE
पहले वाली same error😣😣😣😣

### ISSUE THREAD

**Issue by Venomhash123** [AbirHasan2005/Rename-Bot#17]
![Screenshot_2021-12-03-13-07-27-495_org telegram plus](https://user-images.githubusercontent.com/89146099/144563881-b6016c15-7703-4582-a5be-74b377c7e533.jpg)
![Screenshot_2021-12-03-13-07-41-564_org telegram plus](https://user-images.githubusercontent.com/89146099/144563929-f53e5a6e-674f-45c4-a40a-7fae395cdfe9.jpg)

**Comment by AbirHasan2005** [comment]
☹️☹️☹️

Dekhtahu wait

**Comment by AbirHasan2005** [comment]
Check Now

**Comment by Venomhash123** [comment]
Now working 🤗🤗🤗🤗🤗🤗❤️❤️❤️❤️

**Comment by AbirHasan2005** [comment]
Check karlo koi dusra problem ho to 😂
