### ISSUE TITLE
Heroku Ban issue 

### ISSUE THREAD

**Issue by MrMKN** [AbirHasan2005/Rename-Bot#21]
bro while using this repo i get ban on heroku my two accounts got banned 🙏😥 please fix

**Comment by AbirHasan2005** [comment]
Don't use heroku.

**Comment by MrMKN** [comment]
Bro please suggested best hosting web 🙏😥

**Comment by MrMKN** [comment]
I am big fan of you bro 🥰

**Comment by AbirHasan2005** [comment]
replit.com
