### ISSUE TITLE
user status module

### ISSUE THREAD

**Issue by Naviya2** [AbirHasan2005/Rename-Bot#3]
plz add user status module. it is on the main.py but no module added to helpers

**Comment by AbirHasan2005** [comment]
Wat???
You mean [this](https://github.com/AbirHasan2005/Rename-Bot/blob/b2f69e2a762fd6515a1692e5afd2cafca894610e/main.py#L235)??

**Comment by Naviya2** [comment]
> Wat???
> You mean [this](https://github.com/AbirHasan2005/Rename-Bot/blob/b2f69e2a762fd6515a1692e5afd2cafca894610e/main.py#L235)??

bro it is missing module. .py file missing on your repo check it. i've informed about it.

**Comment by AbirHasan2005** [comment]
Why need module for that?
Maybe u misunderstood something.

Do you mean [this](https://github.com/AbirHasan2005/Rename-Bot/blob/b2f69e2a762fd6515a1692e5afd2cafca894610e/main.py#L235) command??

**Comment by Naviya2** [comment]
> Why need module for that?
> Maybe u misunderstood something.
> 
> Do you mean [this](https://github.com/AbirHasan2005/Rename-Bot/blob/b2f69e2a762fd6515a1692e5afd2cafca894610e/main.py#L235) command??

no bro it is not working i have check with that command also. it is not showing user count or any with /status cmd. check it again

**Comment by AbirHasan2005** [comment]
Maybe u didn't update 👀

**Comment by Naviya2** [comment]
> Maybe u didn't update 👀

oh sorry bro. it i missed your latest update. soeey for wasting your time. i will cloae the issue. sorry

**Comment by AbirHasan2005** [comment]
No problem 😅
