### ISSUE TITLE
broadcast with forward tag is not working

### ISSUE THREAD

**Issue by Naviya2** [AbirHasan2005/Rename-Bot#5]
i have followed your instructions and give True to BROADCAST_AS_COPY var but it is'nt brodcasting with forward tag!! please fix it

**Comment by AbirHasan2005** [comment]
Show Config Screenshot Please.

**Comment by Naviya2** [comment]
> Show Config Screenshot Please.

![Screenshot_20210725_221039_com android chrome](https://user-images.githubusercontent.com/74837844/126906655-8f19e9d7-0eaa-4d0d-81af-52252d50bf32.jpg)

**Comment by AVBotz-TG** [comment]
> > Show Config Screenshot Please.
> 
> ![Screenshot_20210725_221039_com android chrome](https://user-images.githubusercontent.com/74837844/126906655-8f19e9d7-0eaa-4d0d-81af-52252d50bf32.jpg)

Make it "False"
